site_name: Python in 5 Minutes (or less)
nav:
    - index.md
    - basic_types.md
    - numeric.md
    - strings.md
    - lists.md
    - tuples.md
    - dicts.md
    - sets.md


site_author: Juliano Fischer Naves

theme:
    name: readthedocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
